### ISSUE TITLE
Feature request: Expose wizard options in command palette

### ISSUE THREAD

**Issue by FMCorz** [lmscloud-io/mdlcode-docs#10]
It'd be nice if the various commands and utilities offered by the extension, such as the various wizards, could be accessed via the command palette (CTRL + SHIFT + P). I would personally prefer this over having to click on the icon in the sidebar, or searching for "Open wizard" in the commands. Also because the wizard webview does not appear instantly.

**Comment by marinaglancy** [comment]
Hi Fred,
I was trying to keep the number of registered commands in the command palette to the minimum. There is one called "MDLCode: Open Wizard" that currently opens the wizard webview.  There is another command "MDLCode: Run CLI script". When you invoke it, it opens a dropdown with the list of your favourites and the "More..." to open the webview.

What if I do not add all wizard options to the command palette but instead change the behavior of the "MDLCode: Open Wizard" command - instead of opening a webview (that is a little slow sometimes, I agree), it would display a dropdown with all wizard options and the "More..." button in the bottom to open the webview with the wizard directory.

I can also add a possibility to "Favourite" some wizards so that the dropdown only displays the ones that you chose and "More..." will take you to the directory.

**Comment by FMCorz** [comment]
Hi Marina,

I personally do not mind having lots and lots of commands in the command palette. I use it both as a mean to quickly use them, but also to discover what a particular extension offers. If you have a look at gitlens, they defined many commands. However, the solution you are suggesting (dropdown) is a good compromise if you prefer keeping the list as short as possible. Favourites appeal to me less.

Thanks!

**Comment by marinaglancy** [comment]
Thanks for suggestion, Fred.
This is added in v1.0.33 (released today)

I added the option I suggested - the existing command "MDLCode: Open Wizard" now displays a QuickPick menu where you can start typing the wizard name and then click Enter to open it
