### ISSUE TITLE
In Wizard, Create new plugin, add Settings option

### ISSUE THREAD

**Issue by PatLemaire** [lmscloud-io/mdlcode-docs#12]
It would be really usefull to have an option for creating a _settings file_ during wizard process.

**Comment by marinaglancy** [comment]
Hello @PatLemaire , thanks for the suggestion. 
Site admin settings are already on my TODO list. They are a little more complicated because some plugin types have different format for the settings file and different initial contents.

Can you elaborate a little about what you are after? The title of this issue mentions "New plugin" but the description sounds like you are asking for an independent settings wizard. Do you just want a checkbox in the "New plugin" wizard that would create a settings.php file? Or do you want a new wizard type for creating actual settings?

If it's a former one, I do not really see a need for it. It only takes two clicks to create a settings file: after you create a new plugin you right click on the plugin name in the "Plugins" view, then hover over "New file" and then select "settings.php".

![settingsphpinmdlcode](https://github.com/lmscloud-io/mdlcode-docs/assets/836986/10b330b5-773c-46b0-b840-1179169f3d7c)

I would like to keep the number of the options when creating a new plugin to a minimum. There are only options to create something that is actually populated with a contents (like GHA file or basic tests or privacy provider). There are no options to create any empty files and I do not want to start adding them because there are just way too many of possible standard files in moodle plugins.

Like I mentioned above, another problem is that currently if you create the settings.php file in a plugin, it is created absolutely empty, without even any scaffoldings that would be present in db/* files or index.php/view.php files. I plan to add the default contents to these files, for example:
```
defined('MOODLE_INTERNAL') || die();

if ($hassiteconfig) {
}
```

However you were not actually asking about populating initial contents of the settings.php file. So can you describe please, what problem you have and how do you want MDLCode to help you?

**Comment by PatLemaire** [comment]
My starting point was the quick editing of a block-type plugin. I had to rewrite an existing plugin to make it compatible with Moodle 4.1 (the old one had been designed for 3.5). 
So I started using the MDLCode wizard, thinking it would be cleaner ... Then I added my old codes to the skeleton. I spent 2 days trying to figure out why my new version had no settings, despite the dedicated file (settings.php). I thought I was going mad. Finally, I realized that the problem lay in the definition of my block's class (_has_config()_ was missing). My fault, of course! I wanted to start from scratch for this rewrite but it was my mistake to use the MDLCode wizard because I rely too much on automated functions.
I think that if, when creating a new plugin, it were possible to check the "my plugin has settings" option, then, depending on the type of plugin, the wizard would offer a choice of options (checkbox type, drop-down list, etc.) and generate the necessary files and definitions.
I'm fully aware that it won't be an easy task 😅

**Comment by marinaglancy** [comment]
Thank you very much for providing this additional context. This is exactly what I was talking about - some plugin types have their own specific of working with settings.php files.  

Adding this option to the new plugin wizard will definitely take some time and a lot of research (to make it work with all plugin types). 

I think we can have a quick win in this case. What if MDLCode raised a problem when you are inside of the block's settings.php file that says:

- Block class ... does not return true in the has_config() function. This settings file will be ignored by Moodle.

This will help in both cases - when you create a new block plugin and when you add settings to an existing block plugin. 

And I will start working gradually on adding other automation around settings.php files.
